"""Theme configuration for font-charset-stats GUI."""

from __future__ import annotations

from PySide6.QtGui import QColor, QPalette
from PySide6.QtWidgets import QApplication


def _dark_palette() -> QPalette:
    p = QPalette()
    p.setColor(QPalette.Window, QColor(53, 53, 53))
    p.setColor(QPalette.WindowText, QColor(255, 255, 255))
    p.setColor(QPalette.Base, QColor(35, 35, 35))
    p.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    p.setColor(QPalette.ToolTipBase, QColor(25, 25, 25))
    p.setColor(QPalette.ToolTipText, QColor(255, 255, 255))
    p.setColor(QPalette.Text, QColor(255, 255, 255))
    p.setColor(QPalette.Button, QColor(53, 53, 53))
    p.setColor(QPalette.ButtonText, QColor(255, 255, 255))
    p.setColor(QPalette.BrightText, QColor(255, 0, 0))
    p.setColor(QPalette.Link, QColor(42, 130, 218))
    p.setColor(QPalette.Highlight, QColor(42, 130, 218))
    p.setColor(QPalette.HighlightedText, QColor(255, 255, 255))
    p.setColor(QPalette.Disabled, QPalette.WindowText, QColor(128, 128, 128))
    p.setColor(QPalette.Disabled, QPalette.Text, QColor(128, 128, 128))
    p.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(128, 128, 128))
    return p


def apply_theme(app: QApplication) -> None:
    """Apply Fusion style with a dark palette."""
    app.setStyle("Fusion")
    app.setPalette(_dark_palette())


# -- Coverage heatmap colors (BackgroundRole per cell) ------------------

_COVERAGE_PALETTE: list[tuple[float, QColor]] = [
    (0.99, QColor(70, 140, 80)),
    (0.90, QColor(130, 150, 60)),
    (0.70, QColor(180, 150, 50)),
    (0.50, QColor(190, 120, 50)),
    (0.00, QColor(190, 80, 70)),
]

COVERAGE_FG = QColor(255, 255, 255)


def coverage_bg_color(pct: float) -> QColor:
    """Return a background color for the given coverage percentage."""
    for threshold, color in _COVERAGE_PALETTE:
        if pct >= threshold:
            return color
    return _COVERAGE_PALETTE[-1][1]


# -- Batch dialog cell colors -------------------------------------------

BATCH_COLORS: dict[str, QColor] = {
    "high": QColor(70, 140, 80),
    "medium": QColor(180, 150, 50),
    "low": QColor(190, 80, 70),
    "error": QColor(130, 90, 60),
}

BATCH_FG = QColor(255, 255, 255)


# -- Matplotlib chart colors --------------------------------------------

CHART_COLORS: list[str] = [
    "#60a5fa",
    "#f87171",
    "#4ade80",
    "#c084fc",
    "#818cf8",
    "#fbbf24",
    "#34d399",
    "#f472b6",
]

CHART_TEXT_COLOR = "#c0c0c0"


# -- HTML export template -----------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Font Charset Stats Report</title>
<style>
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    max-width: 960px; margin: 0 auto; padding: 2em;
    color: #cdd6f4; background: #1e1e2e;
}}
h1 {{
    color: #cdd6f4; border-bottom: 2px solid #89b4fa; padding-bottom: .3em;
}}
h2 {{ color: #cdd6f4; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #45475a; padding: 8px 12px; text-align: right; }}
th {{ background: #313244; color: #cdd6f4; }}
tr:nth-child(even) {{ background: #181825; }}
tr:hover {{ background: #313244; }}
.name-col {{ text-align: left; font-weight: 600; }}
.bar {{
    display: inline-block; height: 16px; border-radius: 3px;
    margin-right: 6px; vertical-align: middle;
}}
.green  {{ background: #a6e3a1; }}
.yellow {{ background: #f9e2af; }}
.red    {{ background: #f38ba8; }}
.footer {{
    margin-top: 2em; font-size: .85em; color: #6c7086;
    border-top: 1px solid #45475a; padding-top: 1em;
}}
</style>
</head>
<body>
<h1>Font Charset Stats Report</h1>
{content}
<div class="footer">Generated by font-charset-stats</div>
</body>
</html>"""


def build_html(content: str) -> str:
    """Build an HTML document by inserting *content* into the theme template."""
    return _HTML_TEMPLATE.format(content=content)


def coverage_css_class(pct: float) -> str:
    """Return CSS class name for a coverage bar."""
    if pct >= 0.99:
        return "green"
    elif pct >= 0.7:
        return "yellow"
    else:
        return "red"
